version: '2.4'
services:
    db:
        image: mysql:8.0
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - ./docker/mysql/data:/var/lib/mysql
        command: ["--max_allowed_packet=32505856", "--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: backend
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        networks:
            - internal
    php:
        build: ./docker/php-fpm
        ports:
            - "9001:9000"
        volumes:
            - .:/var/www/api:cached
            - ./docker/var/log/api:/var/www/api/var/log:cached
        links:
            - db
            - redis
        extra_hosts:
            - "docker.host:127.0.0.1"
        networks:
            - internal
    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker/var/log/nginx/:/var/log/nginx:cached
        networks:
            - internal
    redis:
        image: sickp/alpine-redis:4.0.6
        volumes:
            - ./docker/redis/data:/data
        ports:
            - "6380:6379"
        networks:
            - internal

networks:
    internal:
        driver: bridge
